### ISSUE TITLE
Call for Mentors 31st August'19

### ISSUE THREAD

**Issue by AhsanAyaz** [nodeschool/karachi#13]
## Call for Mentors

Hey Mentors! 
Our next event is being planned for **31st August'19**. The venue is 10Pearls, Karachi.
Event Link (to be provided)

1) Leave a comment on this issue to join us as a mentor for this coming event! 
2) I'll add you to the list.
3) Please join the [slack channel](https://join.slack.com/t/nodeschoolkarachi/shared_invite/enQtMzI0ODkyOTg1MzE0LTM4MDljODgxYTY1ZGQ2ZTBkNGJmZTg4YmUzNmEyOWE1OWFhMzdiNGQzY2U1ZDU0NDhhNjIyNzkxMjk4ZjEzZDk).

-----
## What is the event about? 
While our previous event (Rest APIs Workshop) focused on getting some hands-on workshops, this will bring even more fun. We're gonna push the boundaries and will go through some new tools and stacks that we can get our hands dirty with. The call for proposals will be started soon.

## Event Flow: 
To be decided

-----

If you're wondering if you should be a PRO in NodeJS to be a mentor, that's not the case for NodeSchool Karachi & NodeSchool in general. **You just need to be familiar with what we're going to present in the talks above so you can guide the attendees if needed.**
We encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page. It will answer most of your questions.

👋

-----

#### Mentors

- [x] @smtaha512
- [x] @narainsagar
- [x] @ZenabKhan
- [x] @SabihRehman
- [x] @BilalAlam173
- [x] @mfaheemakhtar
- [x] @Syed-Saad-Qamar
- [x] @mehdirajani5
- [x] @shaharyar123
- [x] @mashhoodr
- [x] @Faria-Ejaz
- [x] @JavaEria
- [x] @aamirubit
- [x] @Tauqeer1

#### Organizers and volunteers

- [x] @ahsanayaz
- [x] @smkamranqadri

**Comment by smtaha512** [comment]
Interested.

**Comment by AhsanAyaz** [comment]
> Interested.

@smtaha512, added you.

**Comment by narainsagar** [comment]
Finally... Add me too. :)

**Comment by sohaibnehal** [comment]
@AhsanAyaz Sir I am travelling otherwise would love to have joined. Can you please add me on Slack for any further events?

**Comment by BilalAlam173** [comment]
Im Interested

**Comment by mfaheemakhtar** [comment]
Hey! I'm interested too.

**Comment by SabihRehman** [comment]
Interested

**Comment by ZenabKhan** [comment]
Add me in!!!  :D

**Comment by AhsanAyaz** [comment]
@narainsagar , @ZenabKhan , @SabihRehman , @BilalAlam173, @mfaheemakhtar added you.
@sohaibnehal invited you using your email on github. The link is mentioned in the issue as well :)

**Comment by mehdirajani5** [comment]
Add me in.

**Comment by Syed-Saad-Qamar** [comment]
Interested

**Comment by shaharyar123** [comment]
intrested

**Comment by AhsanAyaz** [comment]
@mehdirajani5 @shaharyar123 @Syed-Saad-Qamar added you folks.

**Comment by mashhoodr** [comment]
Count me in!

**Comment by Faria-Ejaz** [comment]
interested

**Comment by JavaEria** [comment]
Interested

**Comment by AhsanAyaz** [comment]
@mashhoodr, @JavaEria , @Faria-Ejaz added you all.

**Comment by aamirubit** [comment]
Interested

**Comment by Tauqeer1** [comment]
Interested

**Comment by AhsanAyaz** [comment]
It's amazing that we've got so many mentors 🎉. Closing the call for mentors now. The mentors added to the issue, please [join the slack channel](https://join.slack.com/t/nodeschoolkarachi/shared_invite/enQtMzI0ODkyOTg1MzE0LTM4MDljODgxYTY1ZGQ2ZTBkNGJmZTg4YmUzNmEyOWE1OWFhMzdiNGQzY2U1ZDU0NDhhNjIyNzkxMjk4ZjEzZDk). We'll continue the conversation there.

**Comment by Mohammad-Quanit** [comment]
Did mentors selection have been done?
