### ISSUE TITLE
Call for Mentors - 7th April 2018

### ISSUE THREAD

**Issue by AhsanAyaz** [nodeschool/karachi#3]
## Call for Mentors

Hey Mentors! 
Our next event is being planned for **7th April 2018**. Venue is Gaditek, Karachi.
[Event Link](https://web.facebook.com/events/162325484581405/).

1) Leave a comment on this issue to join us as a mentor for this coming event! 
2) I'll add you to the list.
3) Please join the [slack channel](https://join.slack.com/t/nodeschoolkarachi/shared_invite/enQtMzI0ODkyOTg1MzE0LTE0YzA2MGU2ZjE3ZDE1YzY3OTIyNjczM2UzNTMyNWRiMTYxNzljMGE0NGIwOTIwZTE0MjQzYTgxMmM2MDBhZWM).

-----
## What is the event about? 
While our previous event (The Chapter Begins) focused on the `learnyounode` workshopper, for this event we will have some hands-on workshops. The target is to get the attendees started with creating APIs with NodeJS. Here are the four talks that we've planned:

1) Initiating a NodeJS app with `Express` &  `MongoDB`
2) Parsing `JSON payload` and saving data in `MongoDB`
3) Parsing `URL Params` and sending back appropriate data
4) Understanding and implementing `File Uploads` with `multer`

## Event Flow: 

3:00 PM - Introduction to Nodeschool
3:10 PM - Introduction to the Mentors
3:25 PM - Workshop 1
3:55 PM - Workshop 2
4:00 - Break
4:20 PM - Workshop 3
4:55 PM - Workshop 4
5:30 - Networking
5:45 - Wrap up

If you're interested in giving a specific talk from above. Do let us know here in the comments. You will have to submit the at least a week prior to the event date.

-----

If you're wondering if you should be a PRO in NodeJS to be a mentor, that's not the case for NodeSchool Karachi & NodeSchool in general. **You just need to be familiar with what we're going to present in the talks above so you can guide the attendees if needed.**
We encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page. It will answer most of your questions.

👋

-----

#### Mentors

- [x] @aitchkhan Workshop on **Understanding and implementing `File Uploads` with `multer`**
- [x] @BilalAlam173 Workshop on **Initiating a NodeJS app with `Express` &  `MongoDB`**
- [x] @adeelhussain Workshop on **Parsing `JSON payload` and saving data in `MongoDB`** 
- [x] @ahmedtehseen Workshop on **Parsing `URL Params` and sending back appropriate data**
- [x] @abdulmoizeng 
- [x] @isaadabbasi 
- [x] @Tauqeer1 
- [x] @ghulamMustafaRaza
- [ ] you?
- [ ] you?

#### Organizers and volunteers

- [x] @ahsanayaz
- [x] @smkamranqadri

**Comment by aitchkhan** [comment]
Im interested in giving talk on 4

**Comment by AhsanAyaz** [comment]
@aitchkhan , adding your name to the list. Please [join the slack channel](https://join.slack.com/t/nodeschoolkarachi/shared_invite/enQtMzA5MTUwODI5OTU0LTRjZTk5OWM2OTdlYTYyNzI3Mzg1OTAzYzk2MmQ0MjNhN2JjY2Q3MzBmNjE4Njg4NTY2ODI2ODk5YTlhZWMyNTU) so we can have a chat about it.

**Comment by aitchkhan** [comment]
Alright, sure will do.

On Feb 27, 2018 5:15 PM, "Ahsan Ayaz" <notifications@github.com> wrote:

@aitchkhan <https://github.com/aitchkhan> , adding your name to the list.
Please join the slack channel
<https://join.slack.com/t/nodeschoolkarachi/shared_invite/enQtMzA5MTUwODI5OTU0LTRjZTk5OWM2OTdlYTYyNzI3Mzg1OTAzYzk2MmQ0MjNhN2JjY2Q3MzBmNjE4Njg4NTY2ODI2ODk5YTlhZWMyNTU>
so we can have a chat about it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nodeschool/karachi/issues/3#issuecomment-368854831>,
or mute
the thread

**Comment by adeelhussain** [comment]
I am in too and avaiable for any of the talk!

**Comment by AhsanAyaz** [comment]
@adeelhussain cool. 
Can you pick from one of the talks? The 4th talk has been picked by @aitchkhan already.

**Comment by BilalAlam173** [comment]
@AhsanAyaz I am in for talk#1

**Comment by AhsanAyaz** [comment]
Okay @BilalAlam173 , 
Adding your name. Let's go through the talk stuff this week sometime. I see you've joined slack already 👍

**Comment by adeelhussain** [comment]
Okay @Ahsan i will do on #2

**Comment by adeelhussain** [comment]
Okay @AhsanAyaz i will do on number 2

**Comment by AhsanAyaz** [comment]
@adeelhussain. Added your name to talk # 2.

**Comment by ahmedtehseen** [comment]
@AhsanAyaz I'm up for talk # 3

**Comment by AhsanAyaz** [comment]
@abdulmoizeng 👍 added your name
@ahmedtehseen thanks. Added your name to the talk. Please join the [slack channel](https://join.slack.com/t/nodeschoolkarachi/shared_invite/enQtMzI0ODkyOTg1MzE0LTE0YzA2MGU2ZjE3ZDE1YzY3OTIyNjczM2UzNTMyNWRiMTYxNzljMGE0NGIwOTIwZTE0MjQzYTgxMmM2MDBhZWM).

**Comment by ahmedtehseen** [comment]
Thanks @AhsanAyaz , Joined Channel.

**Comment by ahmedkhan847** [comment]
If their space available I would love to give tips on validation in nodejs. And loading models dynamically in nodejs.

**Comment by AhsanAyaz** [comment]
Hey @ahmedkhan847, thanks for connecting.
I'd say the plan is finalized but you can join us as a mentor and give these tips to the group of people you're managing on the day for sure. We can certainly talk about having this as a separate talk in our next meetup.

**Comment by isaadabbasi** [comment]
Hi @Ahsan.
Count me in for mentorship if there is any slot left. Otherwise do let me know. 
Thanks!

**Comment by AhsanAyaz** [comment]
@isaadabbasi .
We have slots left. See the description above ☝️.
Bring more cool folks in. Adding you.

**Comment by Tauqeer1** [comment]
Hi @AhsanAyaz  , I would love to join as a mentor and if there is still any slot left for the talk I can give talk on any topic mentioned in the description

Thanks,
Tauqeer Ahmed

**Comment by AhsanAyaz** [comment]
Hi @Tauqeer1 , Added you as a mentor. However, the talks are already taken.

Thanks.

**Comment by ghulamMustafaRaza** [comment]
I'm in :)

**Comment by AhsanAyaz** [comment]
@ghulamMustafaRaza Added you.

**Comment by AhsanAyaz** [comment]
@aitchkhan , @BilalAlam173 , @ahmedtehseen , @adeelhussain . Please make sure to submit your workshop content (with simple slides & GitHub repo) max by 24th March end of day so we can discuss it.
Send the material to ahsan.ubitian@gmail.com

**Comment by ahmedtehseen** [comment]
@AhsanAyaz will do.

**Comment by BilalAlam173** [comment]
@AhsanAyaz acknowledged
